import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-provider";
import { ThemeProvider } from "@/providers/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            {" "}
            <div className="max-w-7xl mx-auto px-4 py-8">
              <header className="mb-8">
                <h1 className="text-2xl md:text-3xl font-semibold">
                  Vehicle Management{" "}
                  <span className="text-blue-300">Prototype</span>
                </h1>
                <p className="text-slate-300">
                  Driver • Admin • Super User flows
                </p>
              </header>
              {children}
              <footer className="mt-16 text-xs text-slate-400">
                Built with Next.js + Tailwind (dummy data, no backend).
              </footer>
            </div>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
